CC ?= cc
CXX ?= CC
F90 ?= ftn
MPICC ?= cc
MPICXX ?= CC
MPIF90 ?= ftn

test: test-mpi-detach.f90 libdetach.so
	$(MPIF90) -fopenmp test-mpi-detach.f90 -L. -Wl,--rpath,. -ldetach -o test

test-loop: test-mpi-detach.f90 libdetach.so
	$(MPIF90) -fopenmp test-mpi-detach-loop.f90 -L. -Wl,--rpath,. -ldetach -o test-loop


libdetach.so: detach.cpp mpi-detach.h
	$(MPICXX) -fopenmp -shared -fPIC detach.cpp -o libdetach.so -g
